# This workflow will build a .NET projecthttps://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# For more information see: https://github.com/Truong1995-svg/Truong1995-svg/tree/main/.github/workflows

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
